name: trezor_mirage
description: A Dart app that communicates via Trezor Protocol.

version: 1.0.0
# repository: https://github.com/nemoforte/trezor-mirage

environment:
  sdk: ^3.1.3

dependencies:
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
